// Generated by scripts/count-baseline.mjs — do not edit by hand.
globalThis.CTS_BASELINE = {
  "countedAt": "2026-09-29",
  "models": {
    "claude-opus-5-5": {
      "file": "claude-opus-5.5.md",
      "total": 158640,
      "groups": {
        "core": {
          "label": "Core",
          "flag": null,
          "kind": null,
          "tokens": 49744,
          "sections": 39
        },
        "memory": {
          "label": "Memory",
          "flag": "enabled_saffron",
          "kind": null,
          "tokens": 19460,
          "sections": 11
        },
        "artifacts": {
          "label": "Artifacts",
          "flag": "preview_feature_uses_artifacts",
          "kind": null,
          "tokens": 13268,
          "sections": 3
        },
        "past_chats": {
          "label": "Past chat search",
          "flag": "enabled_saffron_search",
          "kind": null,
          "tokens": 3921,
          "sections": 4
        },
        "code_files": {
          "label": "Code execution & file creation",
          "flag": "enabled_monkeys_in_a_barrel",
          "kind": null,
          "tokens": 11429,
          "sections": 11
        },
        "web_search": {
          "label": "Web search",
          "flag": "enabled_web_search",
          "kind": null,
          "tokens": 10744,
          "sections": 5
        },
        "research": {
          "label": "Research",
          "flag": "enabled_compass",
          "kind": null,
          "tokens": 1458,
          "sections": 1
        },
        "connectors": {
          "label": "Connectors (Gmail, Calendar, Drive, Docs)",
          "flag": null,
          "kind": "connector",
          "tokens": 44537,
          "sections": 58
        },
        "ai_artifacts": {
          "label": "AI-powered artifacts",
          "flag": "enabled_turmeric",
          "kind": null,
          "tokens": 4079,
          "sections": 1
        }
      }
    }
  }
};
